import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";

const ProductID: NextPage = () => {
  const router = useRouter();

  const idProduct = router.query["id"];

  console.log({
    idProduct,
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Product Id {idProduct}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Product Detail</h1>
        <button
          onClick={() => {
            router.back();
          }}
        >
          Go Back
        </button>
      </main>
    </div>
  );
};

export default ProductID;
