import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next Appaaaa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <main className={styles.main}>
          <h1>On Boarding App</h1>
          <button onClick={() => router.push("/product")}>Go Product</button>
        </main>
      </main>
    </div>
  );
};

export default Home;
